"""Localized connection and onboarding copy."""

EN = {
    "launch.background_started": "TokenTray is running in the background. You can close this terminal. Use 'tokentray stop' to quit.",
    "launch.failed": "Could not start TokenTray ({error}). Check {path}, or run 'tokentray run --foreground'.",
    "launch.pending": "Background start requested; the app is not responding yet. Check {path} if no tray icon appears.",
    "refresh.no_providers": "No connected services to refresh",
    "refresh.provider_done": "{provider} updated",
    "refresh.provider_failed": "{provider} refresh failed: {reason}",
    "refresh.provider_waiting": "{provider} rate limited: waiting to retry",
    "refresh.provider_retained": "{provider}: recent data retained",
    "refresh.reason_limited": "request rate limit",
    "refresh.reason_connection": "connection failed",
    "refresh.reason_expired": "login expired",
    "refresh.reason_unreadable": "credentials unreadable",
    "refresh.reason_schema": "API response changed",
    "refresh.reason_error": "API error",
    "refresh.timestamp": "{month:02d}/{day:02d} {hour:02d}:{minute:02d}",
    "refresh.retry_at": "Rate limited · retry after {time}",
    "refresh.last_update": "Last updated: {time}",
    "refresh.busy": "Refreshing", "refresh.done": "Updated", "refresh.failed": "Refresh failed",
    "connect.title": "Get started with TokenTray",
    "connect.intro": "Install and sign in to the CLI for the service you use.\nConnecting either service is enough.",
    "connect.service": "Service", "connect.cli": "CLI", "connect.auth": "Credentials",
    "connect.next": "Next step", "connect.detected": "Found", "connect.not_found": "Not found",
    "connect.missing": "Missing", "connect.expired": "Expired / sign-in required",
    "connect.expired_message": "Your login has expired. Please sign in again.",
    "connect.unreadable": "Could not read", "connect.unsupported": "Unsupported authentication mode",
    "connect.keychain": "Could not read the keychain. Allow access when macOS asks, then check again.",
    "connect.found": "Found; connection unverified", "connect.connected": "Connected",
    "connect.login": "Log in", "connect.install": "Installation guide",
    "connect.recheck": "Check again", "connect.cancel": "Stop waiting", "connect.copy": "Copy command",
    "connect.waiting": "Waiting for login…", "connect.checking": "Checking connection…",
    "connect.changed": "Credentials changed; checking usage…",
    "connect.network": "Credentials changed, but usage could not be verified. Try refreshing.",
    "connect.timeout": "Stopped waiting. You can finish signing in and refresh at any time.",
    "connect.terminal_missing": "No supported terminal was found. Copy the command and run it in a terminal.",
    "connect.terminal_failed": "Could not open the login terminal. Copy the command or try again.",
    "connect.hint": "Sign in to {provider} in the terminal that opens.",
    "connect.path_hint": "The CLI was not found. If it is installed, check PATH or restart TokenTray.",
    "connect.choice": "[l]og in, [i]nstallation guide, [r]echeck, [s]kip, [p]aste token, [d]isable",
    "connect.manual": "A pasted Claude token expires within hours. Claude Code owns token renewal.",
    "connect.none": "No provider is connected yet. TokenTray will pick up credentials when you sign in.",
    "connect.saved": "Saved to {backend}", "connect.disabled": "Disabled.",
    "connect.empty": "Nothing entered; skipping.", "connect.token": "Access token",
    "connect.account": "ChatGPT account id (optional)",
    "connect.secret_fallback": "No system keyring is available; credentials are stored in an owner-readable file.",
    "connect.autostart": "Start at login", "connect.autostart_question": "Start TokenTray when you log in?",
    "connect.enabled": "Enabled.", "connect.autostart_failed": "Could not enable; see the log.",
    "connect.done": "Done.", "connect.start": "Start TokenTray now?",
}

KO = {
    "launch.background_started": "TokenTray가 백그라운드에서 실행 중이에요. 터미널을 닫아도 됩니다. 종료하려면 'tokentray stop'을 실행하세요.",
    "launch.failed": "TokenTray를 시작하지 못했어요 ({error}). {path}를 확인하거나 'tokentray run --foreground'로 실행하세요.",
    "launch.pending": "백그라운드 시작을 요청했지만 아직 응답이 없어요. 트레이 아이콘이 나타나지 않으면 {path}를 확인하세요.",
    "refresh.no_providers": "갱신할 연결된 서비스가 없어요",
    "refresh.provider_done": "{provider} 갱신 완료",
    "refresh.provider_failed": "{provider} 갱신 실패: {reason}",
    "refresh.provider_waiting": "{provider} 요청 제한: 재시도 대기 중",
    "refresh.provider_retained": "{provider}: 최근 데이터 유지",
    "refresh.reason_limited": "요청 제한",
    "refresh.reason_connection": "연결 실패",
    "refresh.reason_expired": "로그인 만료",
    "refresh.reason_unreadable": "인증 정보 읽기 실패",
    "refresh.reason_schema": "API 응답 변경",
    "refresh.reason_error": "API 오류",
    "refresh.timestamp": "{month}월 {day}일 {hour:02d}시 {minute:02d}분",
    "refresh.retry_at": "요청 제한 · {time} 이후 재시도",
    "refresh.last_update": "마지막 갱신: {time}",
    "refresh.busy": "갱신 중", "refresh.done": "갱신 완료", "refresh.failed": "갱신 실패",
    "connect.title": "TokenTray 시작하기",
    "connect.intro": "사용할 서비스의 CLI를 설치하고 로그인해 주세요.\n둘 중 하나만 연결해도 사용할 수 있어요.",
    "connect.service": "서비스", "connect.cli": "CLI 확인", "connect.auth": "인증 정보",
    "connect.next": "다음 단계", "connect.detected": "발견됨", "connect.not_found": "찾지 못함",
    "connect.missing": "없음", "connect.expired": "만료 / 로그인 필요",
    "connect.expired_message": "로그인이 만료됐어요. 다시 로그인해 주세요.",
    "connect.unreadable": "읽기 실패", "connect.unsupported": "지원하지 않는 인증 방식",
    "connect.keychain": "키체인을 읽지 못했어요. macOS가 물으면 허용한 뒤 다시 확인해 주세요.",
    "connect.found": "발견됨 · 연결 미확인", "connect.connected": "연결됨",
    "connect.login": "로그인 바로가기", "connect.install": "설치 안내",
    "connect.recheck": "다시 확인", "connect.cancel": "대기 취소", "connect.copy": "명령 복사",
    "connect.waiting": "로그인 대기 중…", "connect.checking": "연결 확인 중…",
    "connect.changed": "인증 정보가 바뀌었어요. 사용량을 확인하고 있어요…",
    "connect.network": "인증 정보는 바뀌었지만 사용량을 확인하지 못했어요. 새로고침해 주세요.",
    "connect.timeout": "로그인 대기를 마쳤어요. 로그인을 완료한 뒤 언제든 새로고침할 수 있어요.",
    "connect.terminal_missing": "지원하는 터미널을 찾지 못했어요. 명령을 복사해 터미널에서 실행해 주세요.",
    "connect.terminal_failed": "로그인 터미널을 열지 못했어요. 명령을 복사하거나 다시 시도해 주세요.",
    "connect.hint": "터미널에서 {provider} 로그인을 진행해요.",
    "connect.path_hint": "CLI를 찾지 못했어요. 설치했다면 PATH를 확인하거나 TokenTray를 다시 실행해 주세요.",
    "connect.choice": "[l]로그인, [i]설치 안내, [r]다시 확인, [s]건너뛰기, [p]토큰 입력, [d]비활성화",
    "connect.manual": "직접 입력한 Claude 토큰은 몇 시간 뒤 만료돼요. 토큰 갱신은 Claude Code가 담당해요.",
    "connect.none": "아직 연결된 서비스가 없어요. 로그인하면 TokenTray가 인증 정보를 다시 확인해요.",
    "connect.saved": "{backend}에 저장했어요.", "connect.disabled": "비활성화했어요.",
    "connect.empty": "입력된 값이 없어 건너뛰어요.", "connect.token": "액세스 토큰",
    "connect.account": "ChatGPT 계정 ID (선택)",
    "connect.secret_fallback": "시스템 키링을 사용할 수 없어 소유자만 읽을 수 있는 파일에 인증 정보를 저장해요.",
    "connect.autostart": "로그인 시 시작", "connect.autostart_question": "컴퓨터에 로그인할 때 TokenTray를 시작할까요?",
    "connect.enabled": "활성화했어요.", "connect.autostart_failed": "활성화하지 못했어요. 로그를 확인해 주세요.",
    "connect.done": "설정을 마쳤어요.", "connect.start": "지금 TokenTray를 시작할까요?",
}
