# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller build.

One-dir, not one-file: a one-file build unpacks Qt to a temp directory on every
launch, which for a program that starts at login and then sits idle is a second
of start-up cost and an antivirus scan for no benefit.

Every platform gets two executables from one collection - a `tokentray` for the
CLI and a windowed `tokentray-gui` that autostart uses. On Windows the split is
what keeps logging in from flashing a console window; everywhere else it is what
makes `status`, `doctor` and `autostart` reachable at all from a download, since
the GUI binary starts an event loop instead of parsing arguments.
"""

import re
import sys
from pathlib import Path

BUILD = Path(SPECPATH)
ROOT = BUILD.parent
IS_WINDOWS = sys.platform == "win32"
IS_MACOS = sys.platform == "darwin"

# Read rather than import: the spec is evaluated before the app's dependencies
# are guaranteed importable, and one version string beats three that drift.
VERSION = re.search(
    r'^__version__ = "([^"]+)"',
    (ROOT / "src/tokentray/__init__.py").read_text(encoding="utf-8"),
    re.MULTILINE,
).group(1)

# keyring finds its backends by dynamic import, so PyInstaller cannot see them.
HIDDEN = [
    "keyring.backends.chainer",
    "keyring.backends.fail",
    "keyring.backends.null",
]
if IS_WINDOWS:
    HIDDEN.append("keyring.backends.Windows")
elif IS_MACOS:
    HIDDEN.append("keyring.backends.macOS")
else:
    HIDDEN += ["keyring.backends.SecretService", "keyring.backends.kwallet"]

# Qt ships far more than a tray app needs; dropping these roughly halves the
# bundle. QtNetwork stays: QLocalServer/QLocalSocket carry the IPC channel.
EXCLUDES = [
    "PySide6.QtWebEngineCore", "PySide6.QtWebEngineWidgets", "PySide6.QtWebEngineQuick",
    "PySide6.QtQuick", "PySide6.QtQuick3D", "PySide6.QtQuickWidgets", "PySide6.QtQml",
    "PySide6.Qt3DCore", "PySide6.Qt3DRender", "PySide6.Qt3DAnimation", "PySide6.Qt3DExtras",
    "PySide6.QtMultimedia", "PySide6.QtMultimediaWidgets", "PySide6.QtCharts",
    "PySide6.QtDataVisualization", "PySide6.QtBluetooth", "PySide6.QtNfc",
    "PySide6.QtPositioning", "PySide6.QtLocation", "PySide6.QtSerialPort",
    "PySide6.QtSql", "PySide6.QtTest", "PySide6.QtPdf", "PySide6.QtPdfWidgets",
    "PySide6.QtDesigner", "PySide6.QtHelp", "PySide6.QtUiTools",
    "tkinter", "unittest", "pydoc_data",
]

common = dict(
    pathex=[str(ROOT / "src")],
    binaries=[],
    datas=[(str(ROOT / "src/tokentray/resources"), "tokentray/resources")],
    hiddenimports=HIDDEN,
    hookspath=[],
    runtime_hooks=[],
    excludes=EXCLUDES,
    noarchive=False,
)

# Excluding the Python bindings above does not drop the Qt shared libraries:
# PySide6's hook collects those as binaries, so they survive as dead weight.
# Nothing here is linked from QtCore/QtGui/QtWidgets/QtNetwork, which is all we use.
DROP_LIBS = (
    "Qt6Quick", "Qt6Qml", "Qt6Pdf", "Qt63D", "Qt6WebEngine", "Qt6Multimedia",
    "Qt6Charts", "Qt6DataVisualization", "Qt6Designer", "Qt6Test", "Qt6Sql",
    "Qt6Bluetooth", "Qt6Nfc", "Qt6Positioning", "Qt6Location", "Qt6SerialPort",
    "Qt6Help", "Qt6Spatial", "Qt6ShaderTools", "Qt6VirtualKeyboard",
    "libQt6Quick", "libQt6Qml", "libQt6Pdf", "libQt63D", "libQt6WebEngine",
    "libQt6Multimedia", "libQt6Charts", "libQt6DataVisualization",
    "libQt6Designer", "libQt6Test", "libQt6Sql", "libQt6Bluetooth",
    "libQt6Nfc", "libQt6Positioning", "libQt6Location", "libQt6SerialPort",
    "libQt6Help", "libQt6ShaderTools", "libQt6VirtualKeyboard",
)


def prune(binaries):
    """Drop Qt libraries this app never loads.

    opengl32sw is deliberately kept: it is the software renderer Qt falls back to
    with no GPU driver, which is exactly the VM and remote-desktop case where a
    missing renderer would leave the user with no window at all.
    """
    return [b for b in binaries if not Path(b[0]).name.startswith(DROP_LIBS)]


gui_analysis = Analysis([str(BUILD / "entry_gui.py")], **common)
gui_analysis.binaries = prune(gui_analysis.binaries)
gui_pyz = PYZ(gui_analysis.pure)

# Generated by packaging/make_icons.py and committed. They live outside the
# package because the app never loads them - the tray mark is painted at
# runtime - so shipping them in the wheel would be dead weight.
RESOURCES = ROOT / "packaging/resources"
ICON = str(RESOURCES / ("tokentray.icns" if IS_MACOS else "tokentray.ico"))
if not Path(ICON).exists():
    raise SystemExit(
        f"missing icon asset: {ICON}\n"
        "run: QT_QPA_PLATFORM=offscreen uv run python packaging/make_icons.py"
    )

gui_exe = EXE(
    gui_pyz,
    gui_analysis.scripts,
    [],
    exclude_binaries=True,
    name="tokentray-gui",
    console=False,          # no console window when the OS starts it at login
    icon=ICON,
    disable_windowed_traceback=False,
)

# A second executable for `tokentray status` and friends. `console` only means
# anything on Windows, where it decides whether a console window is allocated;
# on macOS and Linux both binaries are ordinary executables.
cli_analysis = Analysis([str(BUILD / "entry_cli.py")], **common)
cli_analysis.binaries = prune(cli_analysis.binaries)
cli_pyz = PYZ(cli_analysis.pure)
cli_exe = EXE(
    cli_pyz,
    cli_analysis.scripts,
    [],
    exclude_binaries=True,
    name="tokentray",
    console=True,
    icon=ICON,
)

# Order is load-bearing, in two different directions:
#   * COLLECT inherits `console` from the LAST EXE it is handed, and a console
#     collection makes BUNDLE stamp LSBackgroundOnly, which would leave the app
#     unable to show a window at all. So the windowed EXE goes last.
#   * BUNDLE takes CFBundleExecutable from the FIRST executable in its TOC, and
#     COLLECT sorts its own TOC alphabetically - which puts `tokentray` ahead of
#     `tokentray-gui` and would make the .app launch the CLI. So BUNDLE is handed
#     the windowed EXE explicitly, ahead of the collection.
outputs = [cli_exe, gui_exe,
           cli_analysis.binaries, cli_analysis.datas,
           gui_analysis.binaries, gui_analysis.datas]

coll = COLLECT(*outputs, strip=False, upx=False, name="tokentray")

if IS_MACOS:
    app = BUNDLE(
        gui_exe,
        coll,
        name="tokentray.app",
        icon=ICON,
        bundle_identifier="io.github.messy-snail.tokentray",
        info_plist={
            # Menu-bar only: no Dock icon, no app switcher entry.
            "LSUIElement": True,
            "NSHighResolutionCapable": True,
            # PySide6 6.11 ships macosx_13_0 wheels; 12.0 would promise a
            # macOS the app cannot actually start on.
            "LSMinimumSystemVersion": "13.0",
            "CFBundleShortVersionString": VERSION,
            "CFBundleVersion": VERSION,
        },
    )
